// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGuBz4A98aeVlxH1QRMCfmopPk5KfEGQ0',
    appId: '1:294372029646:web:b01016f19bbc050d80cc9f',
    messagingSenderId: '294372029646',
    projectId: 'realix-78410',
    authDomain: 'realix-78410.firebaseapp.com',
    storageBucket: 'realix-78410.appspot.com',
    measurementId: 'G-2CHKLZPGER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZzhFa177CmUO-H5KD9_GCj8BvTOouVoY',
    appId: '1:294372029646:android:9a49a5c1ff2157bf80cc9f',
    messagingSenderId: '294372029646',
    projectId: 'realix-78410',
    storageBucket: 'realix-78410.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCej0l_G4EVV5k8ZpPvrwV8PtZu42EAwd8',
    appId: '1:294372029646:ios:de159eb19ffe83f780cc9f',
    messagingSenderId: '294372029646',
    projectId: 'realix-78410',
    storageBucket: 'realix-78410.appspot.com',
    iosClientId: '294372029646-3sa4hgt43egdlmulf6kagiq58ql4pele.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCej0l_G4EVV5k8ZpPvrwV8PtZu42EAwd8',
    appId: '1:294372029646:ios:981a76f0f437bff380cc9f',
    messagingSenderId: '294372029646',
    projectId: 'realix-78410',
    storageBucket: 'realix-78410.appspot.com',
    iosClientId: '294372029646-n0sqelcgk9186rl07243d0fan4fof0f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
